src/ClassCodeBundle/Entity/Meeting.php
<?php

namespace ClassCodeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert ;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * ClassCodeBundle\Entity\Meeting
 *
 * @ORM\Table(name="meeting")
 * @ORM\Entity(repositoryClass="ClassCodeBundle\Entity\MeetingRepository")
 */
class Meeting
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @var integer $ownerId 
     *     * 
     * @ORM\ManyToOne(targetEntity="People", inversedBy="ownedMeetings")
     * @ORM\JoinColumn(name="ownerId", referencedColumnName="id", nullable=false)
     * @Assert\Type(type="ClassCodeBundle\Entity\People")
     *
     */
    protected $ownerId;
    
    /**
     * @var string $date
     *
     * @ORM\Column(name="date", type="string", length=255 , nullable=true)
     */
    private $date;
    
    /**
     * @var string $time
     *
     * @ORM\Column(name="time", type="string", length=255 , nullable=true)
     */
    private $time;
    
    /**  
     * @var string $structure
     *
     * @ORM\Column(name="structure", type="string", length=255,nullable=true)
     *  
     */
    private $structure;
    
    /**  
     * @var string $street
     *
     * @ORM\Column(name="street", type="text",nullable=true)
     *  
     */
    private $street;  
    
    /**
     * @var string $city
     *
     * @ORM\Column(name="city", type="text", length=255,nullable=true)
     * 
     *  
     */
    private $city;
        
    /**
     * @var string $zipcode
     *
     * @ORM\Column(name="zipcode", type="string", length=255,nullable=true)
     * 
     *  
     */
    private $zipcode;
    
    /**  
     * @var string $country
     *
     * @ORM\Column(name="country", type="string", length=255,nullable=true)
     *  
     */
    private $country;
    
    /**  
     * @var string $state
     *
     * @ORM\Column(name="state", type="string", length=255,nullable=true)
     *  
     */
    private $state;
    
    /**  
     * @var string $formattedAddress
     *
     * @ORM\Column(name="formattedAddress", type="text",nullable=true)
     *  
     */
    private $formattedAddress;
    
    /**
     * @var string $capacity
     *
     * @ORM\Column(name="capacity", type="string", length=255,nullable=true)
     * 
     *  
     */
    private $capacity;
    
    /**
     * @var string $hangoutLink
     *
     * @ORM\Column(name="hangoutLink", type="text",nullable=true)
     * 
     *  
     */
    private $hangoutLink;
    
    /**
     * @var string $more
     *
     * @ORM\Column(name="more", type="text",nullable=true)
     * 
     *  
     */
    private $more;
    
    /**
     * @var string $subject
     *
     * @ORM\Column(name="subject", type="text",nullable=true)
     * 
     *  
     */
    private $subject;
    
    /**
     * @var string $precisions
     *
     * @ORM\Column(name="precisions", type="text",nullable=true)
     * 
     *  
     */
    private $precisions;
  
    /**
     * @ORM\ManyToMany(targetEntity="People", inversedBy="meetings",cascade={"persist"})
     * @ORM\JoinTable(name="meetings_subscribers")
     **/
    private $subscribers;
    
    
    /**
     * @var float $latitude
     *
     * @ORM\Column(name="latitude", type="float", length=255)
     * 
     *  
     */
    private $latitude = 0;
    
    /**
     * @var float $longitude
     *
     * @ORM\Column(name="longitude", type="float", length=255)
     * 
     *  
     */
    private $longitude = 0;
    
    /**
     * @var \DateTime $updated_at
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updated_at;
    
    /**
     * @var string $updated_by
     *
     * @ORM\Column(name="updated_by", type="text",  type="string", length=255, nullable=true)
     */
    private $updated_by;

    public function __construct() {
      $this->subscribers = new ArrayCollection();
    }
     
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
      return $this->id;
    }
    
    /**
     * Get people
     *
     * @return \ClassCodeBundle\Entity\People 
     */
    public function getOwner()
    {
      return $this->ownerId;
    }
    
    /**
     * Set people
     *
     * @param \ClassCodeBundle\Entity\People $people
     * @return GeoLoc
     */
    public function setOwner(\ClassCodeBundle\Entity\People $people)
    {
      $this->ownerId = $people;
      return $this;
    }

    /**
     * Get date
     *
     * @return string 
     */
    public function getDate()
    {
      return $this->date;
    }    
    
    /**
     * Set date
     *
     * @param string $date
     * @return Meeting
     */
    public function setDate($date)
    {
      $this->date = $date;
      return $this;
    }
    
    /**
     * Get time
     *
     * @return string 
     */
    public function getTime()
    {
      return $this->time;
    }    
    
    /**
     * Set time
     *
     * @param string $time
     * @return Meeting
     */
    public function setTime($time)
    {
      $this->time = $time;
      return $this;
    }
    
    /**
     * Get structure
     *
     * @return string 
     */
    public function getStructure()
    {
      return $this->structure;
    }
    
    /**
     * Set structure
     *
     * @param string $structure
     * @return Meeting
     */
    public function setStructure($structure)
    {
      $this->structure = $structure;
      return $this;
    }
    
    /**
     * Get street
     *
     * @return string 
     */
    public function getStreet()
    {
      return $this->street;
    }
    
    /**
     * Set street
     *
     * @param string $street
     * @return Meeting
     */
    public function setStreet($street)
    {
      $this->street = $street;
      return $this;
    }

    /**
     * Get city
     *
     * @return string 
     */
    public function getCity()
    {
      return $this->city;
    }    
    
    /**
     * Set town
     *
     * @param string $city
     * @return Meeting
     */
    public function setCity($city)
    {
      $this->city = $city;
      return $this;
    }
    
    /**
     * Get state
     *
     * @return state 
     */
    public function getState()
    {
      return $this->state;
    }
    
    /**
     * Set state
     *
     * @param string $state
     * @return Meeting
     */
    public function setState($state)
    {
      $this->state = $state;
      return $this;
    }

   /**
     * Get zipcode
     *
     * @return string 
     */
    public function getZipcode()
    {
      return $this->zipcode;
    }
    
    /**
     * Set zipcode
     *
     * @param string $zipcode
     * @return Meeting
     */
    public function setZipcode($zipcode)
    {
      $this->zipcode = $zipcode;
      return $this;
    }

    /**
     * Get country
     *
     * @return string 
     */
    public function getCountry()
    {
      return $this->country;
    }
    
    /**
     * Set country
     *
     * @param string $country
     * @return Meeting
     */
    public function setCountry($country)
    {
      $this->country = $country;
      return $this;
    }

   /**
     * Get formattedAddress
     *
     * @return string 
     */
    public function getFormattedAddress()
    {
      return $this->formattedAddress;
    }
        
    /**
     * Set formattedAddress
     *
     * @param string $formattedAddress
     * @return Meeting
     */
    public function setFormattedAddress($formattedAddress)
    {
      $this->formattedAddress = $formattedAddress;
      return $this;
    }

    /**
     * Get latitude
     *
     * @return float 
     */
    public function getLatitude()
    {
      return $this->latitude;
    }    
    
    /**
     * Set latitude
     *
     * @param float $latitude
     * @return Meeting
     */
    public function setLatitude($latitude)
    {
      $this->latitude = $latitude;
      return $this;
    }

    /**
     * Get longitude
     *
     * @return float 
     */
    public function getLongitude()
    {
      return $this->longitude;
    } 
      
    /**
     * Set longitude
     *
     * @param float $longitude
     * @return Meeting
     */
    public function setLongitude($longitude)
    {
      $this->longitude = $longitude;
      return $this;
    }


    /**
     * Get capacity
     *
     * @return string 
     */
    public function getCapacity()
    {
      return $this->capacity;
    }    
    
    /**
     * Set capacity
     *
     * @param string $capacity
     * @return Meeting
     */
    public function setCapacity($capacity)
    {
      $this->capacity = $capacity;
      return $this;
    }
    
    /**
     * Get hangoutLink
     *
     * @return string 
     */
    public function getHangoutLink()
    {
      return $this->hangoutLink;
    }    
    
    /**
     * Set hangoutLink
     *
     * @param string $hangoutLink
     * @return Meeting
     */
    public function setHangoutLink($hangoutLink)
    {
      $this->hangoutLink = $hangoutLink;
      return $this;
    }
    
    /**
     * Get more
     *
     * @return string 
     */
    public function getMore()
    {
      return $this->more;
    }    
    
    /**
     * Set more
     *
     * @param string $more
     * @return Meeting
     */
    public function setMore($more)
    {
      $this->more = $more;
      return $this;
    }
    
    /**
     * Get subject
     *
     * @return string 
     */
    public function getSubject()
    {
      return $this->subject;
    }    
    
    /**
     * Set subject
     *
     * @param string $subject
     * @return Meeting
     */
    public function setSubject($subject)
    {
      $this->subject = $subject;
      return $this;
    }
    
    /**
     * Get precisions
     *

src/ClassCodeBundle/Resources/views/Meeting/ajax_list.html.twig
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id='meeting_list'>
  <thead>
    <tr>
      <th>{{ 'meeting.subject'|trans }} </th>
      <th>{{ 'meeting.dateTime'|trans }} </th>         
      <th>{{ 'meeting.owner'|trans }} </th>   
      <th>{{ 'meeting.state'|trans }} </th>                                    
    </tr>
  </thead> 
  <tbody>
  {% for m in meetings %}     
    <tr>
      <td>
        {{ m.getSubject }}  
      </td>
      <td>
        {{ m.getDate }} <br>{{ m.getTime }}  
      </td>                    
      <td>
        {{ m.getOwner.getNickName }}  
      </td>
      <td>
        {% if m.getState != "" %}
          {{ m.getState }}  
        {% elseif m.getLatitude ==0 and m.getLongitude ==0 %}
          {{ 'meeting.noloc'|trans }}
        {% endif %}
      </td>
    </tr> 
  {% endfor %}
  </tbody>
</table>

src/ClassCodeBundle/Resources/views/Meeting/list.html.twig
{% extends 'base.html.twig' %}
 
{% block stylesheets %}
  {{ parent() }}
  <link rel="stylesheet" href="{{ asset('js/leaflet-1.3.1/leaflet.css') }}" />
  <link rel="stylesheet" href="{{ asset('js/leaflet-1.3.1/plugins/leaflet.markercluster-1.3.0/dist/MarkerCluster.Default.css') }}" />    
{% endblock %}

{% block body_title %}
    {{ 'meeting.list' | trans }}
{% endblock body_title %}

{% block toplinklist %}
  {% if is_granted('ROLE_ADMIN') %}
    
  {% endif %}
{% endblock toplinklist %}

{% block right_action %}
{% endblock %}
{% block body_inner %}
  <div id="classcodeadmin_content" class="col-md-12" style="display:none;">
    
    <div class="col-sm-12">
      <div id="meetingsMap" class="osMap" style="height:400px;">        
    </div>
    
    <div id='meetings_list_div'>
       {% include '@ClassCode/Meeting/ajax_list.html.twig' %}
    </div>
  </div>
  
  <div id="loader">
    <img src="{{ commons_url }}/images/pictos/loading_40.gif" alt="{{ 'Loading'|trans }}" title="{{ 'Loading'|trans }}">
  </div>

  

{% endblock %}

{% block javascripts %}
 {{ parent() }}
 <script type="text/javascript" src="{{ asset('js/leaflet-1.3.1/leaflet.js') }}"></script> 
 <script type="text/javascript" src="{{ asset('js/leaflet-1.3.1/plugins/leaflet.markercluster-1.3.0/dist/leaflet.markercluster.js') }}"></script> 
 <script>
   $(document).ready(function() {    
      loadDataTable();
      $('#loader').hide();
      $('#classcodeadmin_content').show();
      //map
      var meetingsMap = L.map('meetingsMap',{maxZoom: 18}).setView([46.52863469527167, 2.43896484375], 5),
          markers = L.markerClusterGroup({
                spiderfyOnMaxZoom: true,
                showCoverageOnHover: false,
                zoomToBoundsOnClick: true,
                polygonOptions: {
                    fillColor: '#FFFFFF',
                    color: '#FFFFFF',
                    weight: 0.5,
                    opacity: 1,
                    fillOpacity: 0.5
                    }
            }),
            lat = "",
            lon = "",
            LeafIcon = L.Icon.extend({
                options: {
                    iconSize:     [38, 95],
                    shadowSize:   [50, 64],
                    iconAnchor:   [22, 94],
                    shadowAnchor: [4, 62],
                    popupAnchor:  [-3, -76]
                }
            });
            
      var markerDetail = "";
      var lat;
      var lon;
      {% for m in meetingsWithGeoloc %} 
        {% if m.getLatitude != 0 and m.getLongitude != 0 %}
          lat = "{{ m.getLatitude }}" ;
          lon = "{{ m.getLongitude }}" ;
          if((lat !="0")&&(lon != "0")){          
            markerDetail ="<p class='h4'><b>{{ m.getSubject }}</b></p>";
            markerDetail += "<p class='h5'><b> " + "{{ m.getOwner.getNickName }} " + "</b></p>";
            markerDetail += "<p class='h5'><b> " + "{{ m.getDate }} " + "</b></p>";
            markerDetail += "<p class='h5'><b> " + "{{ m.getTime }} " + "</b></p>";
            markers.addLayer(L.marker(L.latLng(lat, lon)).bindPopup(markerDetail)
                .openPopup());
            meetingsMap.addLayer(markers);
          }
        {% endif %}
      {% endfor %}
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
          maxZoom: 18,
          attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        }).addTo(meetingsMap);
    });
    
    function loadDataTable(){
      $('#meeting_list').dataTable({
        "sDom": "<'row'<'col-md-6'li><'col-md-6'f>r>t<'row'<'col-md-6'><'col-md-6'p>>",        
        "oLanguage": {
          "oPaginate": {
            "sFirst":"{{ 'DataTable.FirstPage'|trans }}",
            "sLast": "{{ 'DataTable.LastPage'|trans }}",
            "sNext": "{{ 'DataTable.Next'|trans }}",
            "sPrevious": "{{ 'DataTable.Previous'|trans }}"                    
          },
          "sInfo": "{{ 'DataTable.Conclusion'|trans }}",
          "sLengthMenu": "{{ 'DataTable.Menu'|trans }}",
          "sSearch": "{{ 'DataTable.Search'|trans }}",       
          "sInfoThousands": " ",
          "sEmptyTable": "{{ 'DataTable.noData'|trans }}",
          "sInfoEmpty": "{{ 'DataTable.noData'|trans }}"
        },
        "aLengthMenu": [[100, 500, 1000,10000, -1], [100, 500, 1000,10000, "{{ 'DataTable.all'|trans }}"]],
        "iDisplayLength": 1000
      });
    }
 </script>
{% endblock %} 

src/ClassCodeBundle/Resources/views/Meeting/meetinginfo.json.twig
   {{ meeting|json_encode()|raw }}

src/ClassCodeBundle/Resources/views/Meeting/queryMeetings.json.twig
   {{ meetings|json_encode()|raw }}